import React from "react";
import { $GlobalContainer, $GlobalTitle } from "Styles/global.style.js";
import Button from "Components/button";
import { $TeamEditWrapper, $TeamEditBtn } from "./teamEdit.style";
import { useRouter } from "next/router";

const TeamEdit = () => {
  const router = useRouter();

  return (
    <>
      <$GlobalContainer>
        <$GlobalTitle>Edit Team</$GlobalTitle>
        <$TeamEditWrapper>
          <div className="position">
            <div>Captain</div>
            <div>Brawler</div>
            <div>Brawler</div>
            <div>Brawler Support</div>
            <div>Support</div>
            <div>Villain</div>
            <div>Battlefield</div>
            <div>Bench</div>
            <div>Bench</div>
            <div>Bench</div>
            <div>Bench</div>
            <div>Bench</div>
          </div>
          <div>
            <div>Goku</div>
            <div>Goku</div>
            <div>Goku</div>
            <div>Goku</div>
            <div>Goku</div>
            <div>Goku</div>
            <div>Goku</div>
            <div>Goku</div>
            <div>Goku</div>
            <div>Goku</div>
            <div>Goku</div>
            <div>Goku</div>
          </div>
          <div>
            <$TeamEditBtn>
              <Button
                btnText="Add"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
              <Button
                btnText="Change"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
            </$TeamEditBtn>
            <$TeamEditBtn>
              <Button
                btnText="Add"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
              <Button
                btnText="Change"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
            </$TeamEditBtn>
            <$TeamEditBtn>
              <Button
                btnText="Add"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
              <Button
                btnText="Change"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
            </$TeamEditBtn>
            <$TeamEditBtn>
              <Button
                btnText="Add"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
              <Button
                btnText="Change"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
            </$TeamEditBtn>
            <$TeamEditBtn>
              <Button
                btnText="Add"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
              <Button
                btnText="Change"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
            </$TeamEditBtn>
            <$TeamEditBtn>
              <Button
                btnText="Add"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
              <Button
                btnText="Change"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
            </$TeamEditBtn>
            <$TeamEditBtn>
              <Button
                btnText="Add"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
              <Button
                btnText="Change"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
            </$TeamEditBtn>
            <$TeamEditBtn>
              <Button
                btnText="Add"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
              <Button
                btnText="Change"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
            </$TeamEditBtn>
            <$TeamEditBtn>
              <Button
                btnText="Add"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
              <Button
                btnText="Change"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
            </$TeamEditBtn>
            <$TeamEditBtn>
              <Button
                btnText="Add"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
              <Button
                btnText="Change"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
            </$TeamEditBtn>
            <$TeamEditBtn>
              <Button
                btnText="Add"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
              <Button
                btnText="Change"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
            </$TeamEditBtn>
            <$TeamEditBtn>
              <Button
                btnText="Add"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
              <Button
                btnText="Change"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
            </$TeamEditBtn>
          </div>
        </$TeamEditWrapper>
        <$TeamEditBtn className="decision">
          <Button
            btnText="Save"
            btnTextColor="black"
            btnColor="orange"
            customBtnClass="leagues"
            redirect="/league/123"
          />
          <Button
            btnText="Cancel"
            btnTextColor="white"
            btnColor="red"
            customBtnClass="leagues"
            btnFunction={() => router.back()}
          />
        </$TeamEditBtn>
      </$GlobalContainer>
    </>
  );
};

export default TeamEdit;
