import React, { useState } from 'react';
import { $GlobalContainer, $GlobalTitle } from 'Styles/global.style.js';
import Button from 'Components/button';
import BackLink from 'Components/back-link/index.js';
import { $TeamEditWrapper } from './teamEdit.style';

const TeamEdit = () => {
  const [edit, setEdit] = useState(false);

  return (
    <>
      <BackLink />
      <$GlobalContainer>
        <$GlobalTitle>Edit Team</$GlobalTitle>
        <$TeamEditWrapper>
          <div className="position">
            <div>Captain</div>
            <div>Brawler</div>
            <div>Brawler</div>
            <div>Brawler Support</div>
            <div>Support</div>
            <div>Villain</div>
            <div>Battlefield</div>
            <div>Bench</div>
            <div>Bench</div>
            <div>Bench</div>
            <div>Bench</div>
            <div>Bench</div>
          </div>
          <div>
            <div>Goku</div>
            <div>Goku</div>
            <div>Goku</div>
            <div>Goku</div>
            <div>Goku</div>
            <div>Goku</div>
            <div>Goku</div>
            <div>Goku</div>
            <div>Goku</div>
            <div>Goku</div>
            <div>Goku</div>
            <div>Goku</div>
          </div>
          <div>
            <div>
              <Button
                btnText="Add"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
              <Button
                btnText="Change"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
            </div>
            <div>
              <Button
                btnText="Add"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
              <Button
                btnText="Change"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
            </div>
            <div>
              <Button
                btnText="Add"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
              <Button
                btnText="Change"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
            </div>
            <div>
              <Button
                btnText="Add"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
              <Button
                btnText="Change"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
            </div>
            <div>
              <Button
                btnText="Add"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
              <Button
                btnText="Change"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
            </div>
            <div>
              <Button
                btnText="Add"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
              <Button
                btnText="Change"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
            </div>
            <div>
              <Button
                btnText="Add"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
              <Button
                btnText="Change"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
            </div>
            <div>
              <Button
                btnText="Add"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
              <Button
                btnText="Change"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
            </div>
            <div>
              <Button
                btnText="Add"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
              <Button
                btnText="Change"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
            </div>
            <div>
              <Button
                btnText="Add"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
              <Button
                btnText="Change"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
            </div>
            <div>
              <Button
                btnText="Add"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
              <Button
                btnText="Change"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
            </div>
            <div>
              <Button
                btnText="Add"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
              <Button
                btnText="Change"
                btnTextColor="black"
                btnColor="orange"
                customBtnClass="small"
                redirect="/league/characters"
              />
            </div>
          </div>
        </$TeamEditWrapper>
      </$GlobalContainer>
    </>
  );
};

export default TeamEdit;
