export const photoCredits = [
  {
    image: '/assets/background/deku-allmight.webp',
    name: 'Deku and All Might',
    creator: '@ermaltahiri',
    platform: 'pixabay.com',
  },
  {
    image: '/assets/background/dragonball.webp',
    name: '5 star dragonball',
    creator: '@axel22',
    platform: 'pixabay.com',
  },
  {
    image: '/assets/background/goku-kamehameha.webp',
    name: 'Goku kamehamaha',
    creator: '@edparanoid',
    platform: 'pixabay.com',
  },
  {
    image: '/assets/background/itachi.webp',
    name: 'Itachi background',
    creator: '@HtcHnm',
    platform: 'pixabay.com',
  },
  {
    image: '/assets/background/kakashi-sharigan.webp',
    name: 'Kakashi sharigan',
    creator: '@HtcHnm',
    platform: 'pixabay.com',
  },
  {
    image: '/assets/background/naruto-rasengan.webp',
    name: 'Naruto rasengan',
    creator: '@HtcHnm',
    platform: 'pixabay.com',
  },
  {
    image: '/assets/background/saitama.webp',
    name: 'Saitama background',
    creator: '@HiteshHtSharma',
    platform: 'pixabay.com',
  },
  {
    image: '/assets/background/vegito.webp',
    name: 'Vegito background',
    creator: '@Felixmh',
    platform: 'pixabay.com',
  },
  {
    image: '/assets/background/young-goku.webp',
    name: 'Young goku',
    creator: '@myartchronicle',
    platform: 'pixabay.com',
  },
  {
    image: '/assets/profile/elizabeth.webp',
    name: 'Elizabeth',
    creator: '@ermaltahiri',
    platform: 'pixabay.com',
  },
  {
    image: '/assets/profile/gaara.webp',
    name: 'Gaara',
    creator: '@Eleatell',
    platform: 'pixabay.com',
  },
  {
    image: '/assets/profile/hinata.webp',
    name: 'Hinata',
    creator: '@iwhydog',
    platform: 'pixabay.com',
  },
  {
    image: '/assets/profile/kakashi.webp',
    name: 'Kakashi',
    creator: '@HtcHnm',
    platform: 'pixabay.com',
  },
  {
    image: '/assets/profile/naruto.webp',
    name: 'Naruto',
    creator: '@Eleatell',
    platform: 'pixabay.com',
  },
  {
    image: '/assets/profile/saitama.webp',
    name: 'Saitama',
    creator: '@eriston13',
    platform: 'pixabay.com',
  },
  {
    image: '/assets/profile/sakura.webp',
    name: 'Sakura',
    creator: '@Eleatell',
    platform: 'pixabay.com',
  },
  {
    image: '/assets/profile/sasuke.webp',
    name: 'Sasuke',
    creator: '@Eleatell',
    platform: 'pixabay.com',
  },
  {
    image: '/assets/profile/sukuna.webp',
    name: 'Sukuna',
    creator: '@TRIFEX',
    platform: 'pixabay.com',
  },
  {
    image: '/assets/icons/share-icon.webp',
    name: 'Share Icon',
    creator: '@IO-Images',
    platform: 'pixabay.com',
  },
  {
    image: '/assets/profile/edward-elric.svg',
    name: 'Edward Elric',
    creator: '@Stban',
    platform: 'freesvg.org',
  },
  {
    image: '/assets/icons/google-icon.webp',
    name: 'Google Icon',
    creator: '@Clovis_Cheminot',
    platform: 'pixabay.com',
  },
  {
    image: '/assets/icons/youtube-icon.webp',
    name: 'Youtube Icon',
    creator: '@joshborup',
    platform: 'pixabay.com',
  },
  {
    image: '/assets/icons/twitter-icon.webp',
    name: 'Twitter Icon',
    creator: '@joshborup',
    platform: 'pixabay.com',
  },
  {
    image: '/assets/icons/facebook-icon.webp',
    name: 'Facebook Icon',
    creator: '@joshborup',
    platform: 'pixabay.com',
  },
  {
    image: '/assets/icons/instagram-icon.webp',
    name: 'Instagram Icon',
    creator: '@joshborup',
    platform: 'pixabay.com',
  },
  {
    image: '/assets/icons/tiktok-icon.webp',
    name: 'Tiktok Icon',
    creator: '@Sayyid96',
    platform: 'pixabay.com',
  },
];

export const allSeries = [
  'DBZ',
  'One Punch Man',
  'Black Clover',
  'One Piece',
  'Solo Leveling',
  'The God of High School',
  'The Seven Deadly Sins',
  'Attack on Titan',
  'Fairy Tail',
  'Hunter x Hunter',
  'Latna Saga: Survival of…',
  'Naruto',
  'Soul Eater',
  'Tensei Slime',
  'Fire Force',
  'Omniscient Reader',
  'The Great Mage Returns',
  'My Hero Academia',
  'Bleach',
  'Death Note',
  'Yu Yu Hakusho',
  'TBATE',
  'Full Metal Alchemist',
  'KonoSuba',
  'Magi',
  'Blue Exorcist',
  'Inuyasha',
  'Jujutsu Kaisen',
  'Gundam Wing',
  'Katekyo Hitman Reborn!',
  'Sailor Moon',
  'Shield Hero',
  'Demon Slayer',
  'Rurouni Kenshin',
  'Digimon',
  'Boondocks',
  'Cowboy Bebop',
  'Dr. Stone',
  'Trigun',
  'Yu-Gi-Oh!',
  'Paranoia Agent',
  'Akira',
  'Berserk',
  'Magic Emperor',
  'Martial Arts Reigns',
  'Versatile Mage',
  'Unordinary',
];
